version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vectordb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./master_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      LANGFUSE_HOST: http://langfuse:3000
      OPENAI_MODEL: "gpt-4o-mini"

  frontend:
    build: ./frontend
    ports:
      - "5555:5555"

  langfuse:
    image: ghcr.io/langfuse/langfuse:sha-23150b6
    restart: always
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/vectordb
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: mysecret
      SALT: mysalt
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  redis_data:
  postgres_data:
