models:
  - type: main
    engine: openai
    model: gpt-4o-mini
  - type: embeddings
    engine: openai
    model: text-embedding-ada-002

rails:
  input:
    flows:
      - self check input
  output:
    flows:
      - self check output
